import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import router from "next/router";
import { useContext, useEffect } from "react";
import Hero from "~/components/homepage/Hero";
import PreExamNavbar from "~/components/preExam/preExamNavbar";
import { api, setToken } from "~/utils/api";
import { TeamContext } from "~/utils/context/teamContext";
import type { TeamContextType } from "~/utils/context/teamContext";
import Guidebook from "~/components/homepage/Guidebook";

const Home: NextPage = () => {
  const { setTeam } = useContext(TeamContext) as TeamContextType;

  const refreshToken = api.user.refreshToken.useMutation({
    onSuccess: (payload) => {
      if (!payload) {
        void router.push("/auth/login");
      } else {
        const { accessToken, username } = payload;

        setTeam(username);
        setToken(accessToken);
      }
    },
    onError: () => {
      void router.push("/auth/login");
    },
  });

  //refresh token upon page load (only once)
  useEffect(() => {
    refreshToken.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css"
          integrity="sha384-vKruj+a13U8yHIkAyGgK1J3ArTLzrFGBbBc0tDp4ad/EyewESeXE/Iv67Aj8gKZ0"
          crossOrigin="anonymous"
        />

        <script
          defer
          src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js"
          integrity="sha384-PwRUT/YqbnEjkZO0zZxNqcxACrXe+j766U2amXcgMg5457rve2Y7I6ZJSm2A0mS4"
          crossOrigin="anonymous"
        ></script>

        <script
          defer
          src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js"
          integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <PreExamNavbar />
      <Hero />
      <Guidebook />
      <section className="relative min-h-[700px] overflow-x-hidden px-20 text-[#223144]">
        <Image
          src="/homepage/background.png"
          alt="bg"
          fill
          className=" -z-10 object-cover"
          quality={100}
        />
        <div className=" flex h-full flex-col items-start ">
          <h1 className=" mt-16 text-5xl font-extrabold">Timeline</h1>
          <div className=" mt-16 flex flex-row items-start">
            {timelineItems.map((item, index) => (
              <div className=" flex flex-row" key={index}>
                <div
                  className={`my-8  flex w-64  ${
                    index % 2 === 0 ? "mt-40 flex-col" : "flex-col-reverse"
                  } `}
                >
                  <div className=" flex h-[64px] w-[64px] items-center justify-center rounded-full bg-[#223344]">
                    <h1 className=" text-4xl font-bold text-white">
                      {index + 1}
                    </h1>
                  </div>
                  {index % 2 === 0 ? (
                    <div className="ml-8 -mt-4 border-l-2 border-[#223344] pt-8 pl-8  ">
                      <h1 className=" mt-4 text-2xl font-extrabold">
                        {item.title}
                      </h1>
                      <h1 className=" mt-2  font-semibold">{item.date}</h1>
                    </div>
                  ) : (
                    <div className="ml-8 -mt-4 border-l-2 border-[#223344] pb-8 pl-8 ">
                      <h1 className=" text-2xl font-extrabold ">
                        {item.title}
                      </h1>
                      <h1 className=" mt-2  mb-4 font-semibold">{item.date}</h1>
                    </div>
                  )}
                </div>
                {index !== timelineItems.length - 1 && (
                  <hr className="relative my-8 -ml-48 mt-48 h-[2px] w-32 border-0 bg-[#223344]" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
};

const timelineItems = [
  {
    title: "Pendaftaran Early Bird",
    date: "1 s.d. 14 Februari 2023",
  },
  {
    title: "Pendaftaran Reguler",
    date: "15 s.d. 28 Februari 2023",
  },
  {
    title: "Warmup Penyisihan",
    date: "8 April 2023",
  },
];

export default Home;
